//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TC_HengJiuGame.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Job
    {
        public System.Guid ID { get; set; }
        public string JobName { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public Nullable<bool> IsDel { get; set; }
        public string JobCode { get; set; }
    }
}
