//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TC_HengJiuGame.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrganizationStructure
    {
        public System.Guid ID { get; set; }
        public string OrgName { get; set; }
        public string OrgCode { get; set; }
        public Nullable<int> Leve { get; set; }
        public Nullable<System.Guid> ParentID { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public Nullable<bool> IsParent { get; set; }
    }
}
