//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TC_HengJiuGame.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public System.Guid ID { get; set; }
        public string UserCode { get; set; }
        public string UserName { get; set; }
        public Nullable<bool> Sex { get; set; }
        public Nullable<System.DateTime> BirthDay { get; set; }
        public string NativePlace { get; set; }
        public string Address { get; set; }
        public string Password { get; set; }
        public string Email { get; set; }
        public string Tel { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public Nullable<System.Guid> JobId { get; set; }
        public Nullable<System.Guid> OrgID { get; set; }
        public string QQ { get; set; }
    }
}
